### ISSUE TITLE
Could not find matching language or fallback

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-klicktipp-gateway#1]
`Could not find matching language or fallback for message ID "XX" and language "de".`

Fehler wird wohl durch das Update vom NotificationCenter auf Version 1.5.17 ausgelöst.

Als Workaround die Version vom NotificationCenter auf 1.5.16 fixieren.
Also ein Downgrade machen.

**Comment by fritzmg** [comment]
See also https://github.com/terminal42/contao-notification_center/issues/223

**Comment by fenepedia** [comment]
Problem is with NotificationCenter `1.5.18` fixed.
