### ISSUE TITLE
Subscribe Aktion integrieren

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-klicktipp-gateway#2]
https://support.klicktipp.com/article/389-application-programming-interface-api#api-subscribe

1. Neue Subscribe-Aktion hinzufügen
2. Vorlage "Update-Aktion"
3. Eingabe im Backend erweitern: (Beispiel siehe Screenshot)

- `$list_id` für Double-Opt-in Prozess (als Pflichtfeld)
- `$tag_id` für Tag-ID (optional, kann auch leer sein)
- `$fields` Parameter eingeben.

**Logik**
Vorerst keine weitere Logik implementieren und testen was passiert, wenn ein Kontakt bereits vorhanden ist.

![screen-20201103_cL9QgzFb@2x](https://user-images.githubusercontent.com/566448/98032101-c8fa7080-1e13-11eb-86c2-fdf350d26db4.jpg)

**Comment by fritzmg** [comment]
Implemented in b6be3b6 and ready to test.

**Comment by fenepedia** [comment]
**Fehlermeldung**:
`Kazin8\KlickTipp\Connector: Subscriber search failed: Not found : Diesen Empfänger gibt es nicht.`

Problem ist wohl der Aufruf der falschen Funktion:
https://github.com/fenepedia/contao-klicktipp-gateway/blob/b6be3b6633fc8c1459ece441fc2302e803305356/src/Gateway/KlickTippGateway.php#L76

Sollte wohl `subscribe` anstatt `subscriber_update` aufgerufen werden.

**Comment by fenepedia** [comment]
Zusätzlich bitte folgende kleine Korrekturen beim Text:

- Feld: Tag
Bitte noch dahinter `ID` schreiben
Also Tag ID

- Parameter
Bitte unterhalb statt "Parameter für den API Request."
Neu: Parameter für API-Request: Schlüssel = Klick-Tipp Parameter für API | Wert = Formularfeld (##form_fieldname##)

**Comment by fritzmg** [comment]
> * Bitte noch dahinter `ID` schreiben
>    Also Tag ID

Das wäre aber nicht ganz korrekt, denn man kann entweder eine Tag ID oder einen Tag hinein schreiben.

**Comment by fritzmg** [comment]
> **Fehlermeldung**:
> `Kazin8\KlickTipp\Connector: Subscriber search failed: Not found : Diesen Empfänger gibt es nicht.`
> 
> Problem ist wohl der Aufruf der falschen Funktion:
> 
> https://github.com/fenepedia/contao-klicktipp-gateway/blob/b6be3b6633fc8c1459ece441fc2302e803305356/src/Gateway/KlickTippGateway.php#L76

Ist nun in 0950eb7 behoben :)

**Comment by fritzmg** [comment]
> * Bitte unterhalb statt "Parameter für den API Request."
>   Neu: Parameter für API-Request: Schlüssel = Klick-Tipp Parameter für API | Wert = Formularfeld (##form_fieldname##)

Das Feld wird aber mit der Funktion `subscriber_update` und `subscribe` geteilt. Passt diese Translation dann für beide Varianten? Ich würde eher in der Dokumentation der Extension näher erklären, was man dort eintragen sollte.

**Comment by fenepedia** [comment]
> Das Feld wird aber mit der Funktion `subscriber_update` und `subscribe` geteilt. Passt diese Translation dann für beide Varianten? Ich würde eher in der Dokumentation der Extension näher erklären, was man dort eintragen sollte.

OK. Als Hilfe wäre dann folgender Text sinnvoll.
`Parameter für API-Request. Schlüssel = KlickTipp | Wert = Contao`

**Comment by fritzmg** [comment]
Übersetzung ist nun geändert!

**Comment by fenepedia** [comment]
Feature getestet und in Release 1.1.0 freigegeben.
