### ISSUE TITLE
Änderung der E-Mail-Adresse ermöglichen

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-klicktipp-gateway#5]
Aktuell bietet die Funktion `subscriber_update` nur Änderung der verschiedenen Felder an. Eine Änderung der E-Mail-Adresse des Kontakts ist damit derzeit nicht möglich.

Die E-Mail-Adressenänderung muss zusätzlich implementiert werden:
Doku siehe: https://support.klicktipp.com/article/389-application-programming-interface-api#api-subscriber-update

```
$newemail = 'newemailaddress@domain.com';
…

$updated = $connector->subscriber_update($subscriber_id, $fields, $newemail, $newsmsnumber);
```

## Umsetzung wie am 06.04.2022 besprochen
- Erweiterung der Funktion `subscriber_update`
- E-Mail-Adresse wird über das Keyword/Schlüssel `email` gefiltert 
- Doku siehe: https://support.klicktipp.com/article/389-application-programming-interface-api#api-subscriber-update
- Vor dem Update der Daten bei KlickTipp wird das Daten-Array auf den Schlüssel `email` geprüft. Wenn dieser vorhanden ist, dann wird die Mail-Adresse geändert. Parameter `$newemail`

**Comment by fritzmg** [comment]
@fenepedia teste das bitte mal mit dem aktuellen `dev-master` branch.

**Comment by contaoacademy** [comment]
@fritzmg Die Adressenänderung funktioniert, allerdings wird bei jeder Änderung eine E-Mail mit einer Bestätigung gesendet. Das möchte ich eigentlich verhindern. Gibt es die Option auch zusätzlich einen Opt-In-Prozess als Paramenter anzugeben?

**Comment by fenepedia** [comment]
@fritzmg Die Adressenänderung funktioniert, allerdings wird bei jeder Änderung eine E-Mail mit einer Bestätigung gesendet. Das möchte ich eigentlich verhindern. Gibt es die Option auch zusätzlich einen Opt-In-Prozess als Paramenter anzugeben?

**Comment by fritzmg** [comment]
[Hier](https://support.klicktipp.com/article/389-application-programming-interface-api#api-subscriber-update) steht zumindest keine solche Möglichkeit. Evt. kannst du das bei KlickTipp mal nachfragen, ob das funktioniert? Aber ich kann mir vorstellen, dass KlickTipp das aus Sicherheitsgründen nicht erlaubt.

**Comment by fenepedia** [comment]
Es gibt eine Möglichkeit, dazu ist allerdings ein [Enterprise-Account](https://fene.app/klicktipp-enterprise) nötig.

**Comment by fenepedia** [comment]
Funktioniert. Ich schließe das Ticket und ergänze ein Release-Tag.
