### ISSUE TITLE
Login-Problem bei Passwörtern mit bestimmten Zeichen

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-klicktipp-gateway#6]
Der Login über die Schnittstelle bringt folgende Fehlermeldung:
`Kazin8\KlickTipp\Connector: Login failed: Unauthorized : Falscher Benutzername oder falsches Passwort.`

Nach ein paar Tests konnte ich herausfinden, dass das es wohl an bestimmten Zeichen im Passwort liegt.
Bei Verwendung des Zeichens `#` im Passwort, schlägt der Login fehl.

Aktuell ist unklar ob das Problem an der Contao-Erweiterung liegt, am Paket https://github.com/kazin8/klick-tipp oder an der KlickTipp API selbst.

**Comment by fritzmg** [comment]
Bitte mit `dev-master` nochmal testen (19ed77f2434ede2e4b1a1a99935da991a2e7c042). Nach dem Update muss aber Benutzername und Kennwort der API im Backend nochmal neu abgespeichert werden.

**Comment by fenepedia** [comment]
Ich kann das fehlerhafte Verhalten leider mit der 1.1 gar nicht mehr reproduzieren. Da es mit der 1.2 schon veröffentlicht wurde, würde ich das Ticket schließen. Außer das Problem tritt in Zukunft noch mal auf.
