### ISSUE TITLE
Kompatibilität mit Contao 5 und Notification Center 2.0 herstellen

### ISSUE THREAD

**Issue by fenepedia** [fenepedia/contao-klicktipp-gateway#8]
Derzeit ist die Erweiterung nicht mit Contao 5 und dem Notification Center 2.0 kompatibel. Wir prüfen derzeit den Aufwand.

**Comment by fritzmg** [comment]
Done in https://github.com/fenepedia/contao-klicktipp-gateway/commit/a22943af8b47b3a50bc16a589c4f731305a392ce (though still needs testing).

**Comment by fenepedia** [comment]
Implemented in Version 2.0.0
